<a href="https://colab.research.google.com/github/Bala-452/LGMVIP-Web/blob/main/regg_restaurant_revenue_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('train.csv.zip')
xtest=pd.read_csv('test.csv.zip')

In [ ]:
df.drop(columns=['Id'])

Open Date        City  City Group Type  P1   P2   P3   P4  P5  P6  ...  \
0    07/17/1999    İstanbul  Big Cities   IL   4  5.0  4.0  4.0   2   2  ...   
1    02/14/2008      Ankara  Big Cities   FC   4  5.0  4.0  4.0   1   2  ...   
2    03/09/2013  Diyarbakır       Other   IL   2  4.0  2.0  5.0   2   3  ...   
3    02/02/2012       Tokat       Other   IL   6  4.5  6.0  6.0   4   4  ...   
4    05/09/2009   Gaziantep       Other   IL   3  4.0  3.0  4.0   2   2  ...   
..          ...         ...         ...  ...  ..  ...  ...  ...  ..  ..  ...   
132  06/25/2008     Trabzon       Other   FC   2  3.0  3.0  5.0   4   2  ...   
133  10/12/2006       İzmir  Big Cities   FC   4  5.0  4.0  4.0   2   3  ...   
134  07/08/2006     Kayseri       Other   FC   3  4.0  4.0  4.0   2   3  ...   
135  10/29/2010    İstanbul  Big Cities   FC   4  5.0  4.0  5.0   2   2  ...   
136  09/01/2009    İstanbul  Big Cities   FC   4  5.0  3.0  5.0   2   2  ...   

     P29  P30  P31  P32  P33  P34  P35  P36  P37    revenue  
0    3.0    5    3    4    5    5    4    3    4  5653753.0  
1    3.0    0    0    0    0    0    0    0    0  6923131.0  
2    3.0    0    0    0    0    0    0    0    0  2055379.0  
3    7.5   25   12   10    6   18   12   12    6  2675511.0  
4    3.0    5    1    3    2    3    4    3    3  4316715.0  
..   ...  ...  ...  ...  ...  ...  ...  ...  ...        ...  
132  3.0    0    0    0    0    0    0    0    0  5787594.0  
133  3.0    0    0    0    0    0    0    0    0  9262754.0  
134  3.0    0    0    0    0    0    0    0    0  2544857.0  
135  3.0    0    0    0    0    0    0    0    0  7217634.0  
136  3.0    0    0    0    0    0    0    0    0  6363241.0  

[137 rows x 42 columns]

In [ ]:
df.columns

Index(['Id', 'Open Date', 'City', 'City Group', 'Type', 'P1', 'P2', 'P3', 'P4',
       'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15',
       'P16', 'P17', 'P18', 'P19', 'P20', 'P21', 'P22', 'P23', 'P24', 'P25',
       'P26', 'P27', 'P28', 'P29', 'P30', 'P31', 'P32', 'P33', 'P34', 'P35',
       'P36', 'P37', 'revenue'],
      dtype='object')

In [ ]:
df.describe()

Id          P1          P2          P3          P4          P5  \
count  137.000000  137.000000  137.000000  137.000000  137.000000  137.000000   
mean    68.000000    4.014599    4.408759    4.317518    4.372263    2.007299   
std     39.692569    2.910391    1.514900    1.032337    1.016462    1.209620   
min      0.000000    1.000000    1.000000    0.000000    3.000000    1.000000   
25%     34.000000    2.000000    4.000000    4.000000    4.000000    1.000000   
50%     68.000000    3.000000    5.000000    4.000000    4.000000    2.000000   
75%    102.000000    4.000000    5.000000    5.000000    5.000000    2.000000   
max    136.000000   12.000000    7.500000    7.500000    7.500000    8.000000   

               P6          P7          P8          P9  ...         P29  \
count  137.000000  137.000000  137.000000  137.000000  ...  137.000000   
mean     3.357664    5.423358    5.153285    5.445255  ...    3.135036   
std      2.134235    2.296809    1.858567    1.834793  ...    1.680887   
min      1.000000    1.000000    1.000000    4.000000  ...    0.000000   
25%      2.000000    5.000000    4.000000    4.000000  ...    2.500000   
50%      3.000000    5.000000    5.000000    5.000000  ...    3.000000   
75%      4.000000    5.000000    5.000000    5.000000  ...    3.000000   
max     10.000000   10.000000   10.000000   10.000000  ...    7.500000   

              P30         P31         P32         P33         P34         P35  \
count  137.000000  137.000000  137.000000  137.000000  137.000000  137.000000   
mean     2.729927    1.941606    2.525547    1.138686    2.489051    2.029197   
std      5.536647    3.512093    5.230117    1.698540    5.165093    3.436272   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      4.000000    3.000000    3.000000    2.000000    3.000000    4.000000   
max     25.000000   15.000000   25.000000    6.000000   24.000000   15.000000   

              P36         P37       revenue  
count  137.000000  137.000000  1.370000e+02  
mean     2.211679    1.116788  4.453533e+06  
std      4.168211    1.790768  2.576072e+06  
min      0.000000    0.000000  1.149870e+06  
25%      0.000000    0.000000  2.999068e+06  
50%      0.000000    0.000000  3.939804e+06  
75%      3.000000    2.000000  5.166635e+06  
max     20.000000    8.000000  1.969694e+07  

[8 rows x 39 columns]

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
l=[i for i in df.columns if df[i].dtype=='object']
for i in l:
  df[i]= label_encoder.fit_transform(df[i])

In [ ]:
a=[i for i in xtest.columns if xtest[i].dtype=="object"]
for i in a:
  xtest[i]=label_encoder.fit_transform(xtest[i])

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
y

0      5653753.0
1      6923131.0
2      2055379.0
3      2675511.0
4      4316715.0
         ...    
132    5787594.0
133    9262754.0
134    2544857.0
135    7217634.0
136    6363241.0
Name: revenue, Length: 137, dtype: float64

In [ ]:
x.shape

(137, 42)

In [ ]:
y.shape

(137,)

In [ ]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
xtest=st.fit_transform(xtest)
xtest

array([[-1.73203349, -1.59301097,  0.20983168, ..., -0.56765883,
        -0.5173456 , -0.58041125],
       [-1.73199885, -1.12184544, -0.31202557, ..., -0.56765883,
        -0.5173456 , -0.58041125],
       [-1.73196421,  1.04327231, -1.4506232 , ..., -0.56765883,
        -0.5173456 , -0.58041125],
       ...,
       [ 1.73196421,  1.70514769,  0.96889678, ...,  0.67120965,
         0.53369453,  0.61201043],
       [ 1.73199885,  0.85256246,  0.96889678, ..., -0.56765883,
        -0.5173456 , -0.58041125],
       [ 1.73203349,  0.77403487,  0.96889678, ...,  0.67120965,
         0.00817446, -0.58041125]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-1.71945391, -0.15950748,  0.88075847, ...,  0.57563408,
         0.18982104,  1.61595083],
       [-1.69416782, -1.25723944, -1.49685552, ..., -0.59268991,
        -0.53255348, -0.62592526],
       [-1.66888173, -1.15512483, -0.90245203, ..., -0.59268991,
        -0.53255348, -0.62592526],
       ...,
       [ 1.66888173, -0.26162208, -0.22313374, ..., -0.59268991,
        -0.53255348, -0.62592526],
       [ 1.69416782,  0.96375313,  0.88075847, ..., -0.59268991,
        -0.53255348, -0.62592526],
       [ 1.71945391,  0.35106552,  0.88075847, ..., -0.59268991,
        -0.53255348, -0.62592526]])

In [ ]:
# from sklearn.preprocessing import StandardScaler
sy=StandardScaler()
y=pd.DataFrame(y)
y=sy.fit_transform(y)
y

array([[ 4.67620885e-01],
       [ 9.62186442e-01],
       [-9.34350664e-01],
       [-6.92739475e-01],
       [-5.33058546e-02],
       [ 2.19658233e-01],
       [ 2.77833615e-01],
       [ 1.48342577e-02],
       [ 1.94402770e-01],
       [ 3.85986933e-01],
       [-2.76000577e-01],
       [ 2.75782306e-01],
       [-1.05931693e+00],
       [ 1.38005969e-01],
       [-9.56278836e-01],
       [-4.81021306e-01],
       [ 5.93902192e+00],
       [ 1.46493971e+00],
       [ 3.44414888e-01],
       [-9.47381255e-01],
       [ 4.17743470e-01],
       [-1.28714830e+00],
       [-1.93811427e-01],
       [-5.66677618e-01],
       [ 1.73399053e+00],
       [-2.62954012e-01],
       [-8.51734889e-01],
       [ 3.82499512e-01],
       [ 9.83430252e-02],
       [-3.91810949e-01],
       [-5.63120066e-01],
       [-9.33078579e-01],
       [-4.64265630e-01],
       [-8.11302070e-01],
       [-1.37395534e-01],
       [-2.14149979e-01],
       [-5.55301322e-01],
       [-6.67346090e-01],
       [ 3.9

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_valid,y_train,y_valid=train_test_split(x,y,test_size=0.2,random_state=10)

In [ ]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam
model=Sequential()
model.add(Dense(units=25,input_dim=42,activation="tanh"))
model.add(Dense(units=30,activation="relu"))
model.add(Dense(units=30,activation="relu"))
model.add(Dense(1))

In [ ]:
model.compile(loss='mse',optimizer=Adam(learning_rate=0.001),metrics=['RootMeanSquaredError'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 25)                1075      
                                                                 
 dense_1 (Dense)             (None, 30)                780       
                                                                 
 dense_2 (Dense)             (None, 30)                930       
                                                                 
 dense_3 (Dense)             (None, 1)                 31        
                                                                 
Total params: 2,816
Trainable params: 2,816
Non-trainable params: 0
_________________________________________________________________


In [ ]:

model.fit(x_train,y_train,epochs=50,validation_data=(x_valid,y_valid))

Epoch 1/50
4/4 [==============================] - 7s 99ms/step - loss: 0.9631 - root_mean_squared_error: 0.9814 - val_loss: 1.4135 - val_root_mean_squared_error: 1.1889
Epoch 2/50
4/4 [==============================] - 0s 12ms/step - loss: 0.8870 - root_mean_squared_error: 0.9418 - val_loss: 1.4214 - val_root_mean_squared_error: 1.1922
Epoch 3/50
4/4 [==============================] - 0s 12ms/step - loss: 0.8496 - root_mean_squared_error: 0.9218 - val_loss: 1.4009 - val_root_mean_squared_error: 1.1836
Epoch 4/50
4/4 [==============================] - 0s 11ms/step - loss: 0.8169 - root_mean_squared_error: 0.9038 - val_loss: 1.3906 - val_root_mean_squared_error: 1.1793
Epoch 5/50
4/4 [==============================] - 0s 12ms/step - loss: 0.7855 - root_mean_squared_error: 0.8863 - val_loss: 1.3791 - val_root_mean_squared_error: 1.1743
Epoch 6/50
4/4 [==============================] - 0s 13ms/step - loss: 0.7589 - root_mean_squared_error: 0.8711 - val_loss: 1.3622 - val_root_mean_squared_

In [ ]:
mse,rmse = model.evaluate(x_train,y_train)
print(rmse)

4/4 [==============================] - 0s 3ms/step - loss: 0.2145 - root_mean_squared_error: 0.4632
0.4631885886192322


In [ ]:
y_pred=model.predict(xtest)

3125/3125 [==============================] - 5s 1ms/step


In [ ]:
y_prd=sy.inverse_transform(y_pred)

In [ ]:
y_prd

array([[4740309.5],
       [2843678. ],
       [3907684.5],
       ...,
       [6206423.5],
       [7257390.5],
       [6862642. ]], dtype=float32)

In [ ]:
y_prd=pd.DataFrame(y_prd)
y_prd.to_csv('pred1.csv')

In [ ]:
y_prd

0
0      4740309.500
1      2843678.000
2      3907684.500
3      3467078.250
4      4920405.000
...            ...
99995  4171839.500
99996  1980839.125
99997  6206423.500
99998  7257390.500
99999  6862642.000

[100000 rows x 1 columns]

In [ ]:
y_prd.to_csv('predtest.csv')